# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_xiaomi_msm8998.git
          kernel-branch: lineage-22.2
          config: sagit_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          lxc: true
          lxc-patch: true
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
